apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:  
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:  
        - name: cont1
          image: rakshitsen/central-image:tag
          ports:
            - containerPort: 80
